# Sarcasm detection task
runner:
  total_steps: 3000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 50
  eval_step: 50
  save_step: 50
  max_keep: 60
  eval_dataloaders: 
    - dev
    - test
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 5.0e-6

# # comment the whole scheduler config block to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 5000

downstream_expert: 
  datarc:
    num_workers: 4
    train_batch_size: 8
    eval_batch_size: 1
    max_timestep: 128000

  # Please refer to https://github.com/iver56/audiomentations for more augmentation options
  augmentation:
    AddGaussianSNR:
      min_snr_in_db: 0
      max_snr_in_db: 3
      p: 0.5

    TimeStretch:
      min_rate: 0.8
      max_rate: 1.25
      p: 0.5

    # Shift:
    #   min_fraction: -0.5
    #   max_fraction: 0.5
    #   p: 0.5

    PitchShift:
      min_semitones: -4
      max_semitones: 4
      p: 0.5

    Gain:
      min_gain_in_db: -12
      max_gain_in_db: 12
      p: 0.5

  modelrc:
    project: True
    projector_dim: 768
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
