# Sarcasm detection task
runner:
  total_steps: 1000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 50
  eval_step: 50
  save_step: 50
  max_keep: 1
  eval_dataloaders: 
    - dev
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 3.0e-5

downstream_expert: 
  datarc:
    num_workers: 12
    train_batch_size: 32
    eval_batch_size: 8
    max_timestep: 128000
    speaker_dependent: False

  # Please refer to https://github.com/iver56/audiomentations for more augmentation options
  augmentation:
    AddGaussianSNR:
      min_snr_in_db: 0
      max_snr_in_db: 3
      p: 0.5

    TimeStretch:
      min_rate: 0.8
      max_rate: 1.25
      p: 0.5

    PitchShift:
      min_semitones: -4
      max_semitones: 4
      p: 0.5

    Gain:
      min_gain_in_db: -12
      max_gain_in_db: 12
      p: 0.5

  modelrc:
    project: True
    projector_dim: 64
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
