# Sarcasm detection task
runner:
  total_steps: 500
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 20
  eval_step: 20
  save_step: 20
  max_keep: 1
  eval_dataloaders: 
    - dev
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 3.0e-5

# # comment the whole scheduler config block to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 5000

downstream_expert: 
  datarc:
    num_workers: 12
    train_batch_size: 32
    eval_batch_size: 1
    max_timestep: 128000
    speaker_dependent: False

  # Please refer to https://github.com/iver56/audiomentations for more augmentation options
  augmentation:
    AddGaussianNoise:
      min_amplitude: 0.001
      max_amplitude: 0.015
      p: 0.5

    TimeStretch:
      min_rate: 0.8
      max_rate: 1.25
      p: 0.5

    Shift:
      min_fraction: -0.5
      max_fraction: 0.5
      p: 0.5

    Gain:
      min_gain_in_db: -12
      max_gain_in_db: 12
      p: 0.5

  modelrc:
    projector_dim: 64
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
