# Sarcasm detection task
runner:
  eval_dataloaders: 
    - dev

downstream_expert: 
  datarc:
    num_workers: 12
    train_batch_size: 32
    eval_batch_size: 8
    max_timestep: 128000
    speaker_dependent: False

  modelrc:
    svm_c: 10